services:
  app:
    container_name: hire_sphere_server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev-network
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - dev-network
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      

volumes:
  postgres_data:
      
networks:
  dev-network: {}