services:
  app:
    image:
      hiresphere:latest
    networks:
      - dev-network
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./prisma:/usr/src/app/prisma
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - dev-network
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "postgres_data:/var/lib/postgres/data"
      

volumes:
  postgres_data:
      
networks:
  dev-network: {}